<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\com.chrome.devtools.json" />
    <Content Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\package.json" />
    <Content Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\_metadata.json" />
    <Content Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps_ssr\package.json" />
    <Content Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps_ssr\_metadata.json" />
    <Content Include="Protofilo\.vscode\extensions.json" />
    <Content Include="Protofilo\.vscode\launch.json" />
    <Content Include="Protofilo\.vscode\tasks.json" />
    <Content Include="Protofilo\node_modules\ordered-binary\.idea\modules.xml" />
    <Content Include="Protofilo\node_modules\ordered-binary\.nyc_output\5b6bd808-0399-4ee6-9395-344688761dfa.json" />
    <Content Include="Protofilo\node_modules\ordered-binary\.nyc_output\processinfo\5b6bd808-0399-4ee6-9395-344688761dfa.json" />
    <Content Include="Protofilo\node_modules\ordered-binary\.nyc_output\processinfo\index.json" />
    <Content Include="Protofilo\node_modules\zod-to-json-schema\.github\CR_logotype-full-color.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\.tsbuildinfo" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\angular-compiler.db" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\angular-compiler.db-lock" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_common.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_common.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_core.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_core.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_platform-browser.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_platform-browser.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_router.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\%40angular_router.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-BTOMYQIT.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-BTOMYQIT.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-K7VHUFL4.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-K7VHUFL4.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-WDMUDEB6.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-WDMUDEB6.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-WU4SUHAZ.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\chunk-WU4SUHAZ.js.map" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\zone__js.js" />
    <None Include="Protofilo\.angular\cache\20.3.35\Protofilo\vite\deps\zone__js.js.map" />
    <None Include="Protofilo\.git\COMMIT_EDITMSG" />
    <None Include="Protofilo\.git\config" />
    <None Include="Protofilo\.git\description" />
    <None Include="Protofilo\.git\HEAD" />
    <None Include="Protofilo\.git\hooks\applypatch-msg.sample" />
    <None Include="Protofilo\.git\hooks\commit-msg.sample" />
    <None Include="Protofilo\.git\hooks\fsmonitor-watchman.sample" />
    <None Include="Protofilo\.git\hooks\post-update.sample" />
    <None Include="Protofilo\.git\hooks\pre-applypatch.sample" />
    <None Include="Protofilo\.git\hooks\pre-commit.sample" />
    <None Include="Protofilo\.git\hooks\pre-merge-commit.sample" />
    <None Include="Protofilo\.git\hooks\pre-push.sample" />
    <None Include="Protofilo\.git\hooks\pre-rebase.sample" />
    <None Include="Protofilo\.git\hooks\pre-receive.sample" />
    <None Include="Protofilo\.git\hooks\prepare-commit-msg.sample" />
    <None Include="Protofilo\.git\hooks\push-to-checkout.sample" />
    <None Include="Protofilo\.git\hooks\sendemail-validate.sample" />
    <None Include="Protofilo\.git\hooks\update.sample" />
    <None Include="Protofilo\.git\index" />
    <None Include="Protofilo\.git\info\exclude" />
    <None Include="Protofilo\.git\logs\HEAD" />
    <None Include="Protofilo\.git\logs\refs\heads\master" />
    <None Include="Protofilo\.git\objects\04\df34cfe778571fb16bc783911a7c060fa26f59" />
    <None Include="Protofilo\.git\objects\0a\8200a0464ec1e422b763c162168be8dcd4e93b" />
    <None Include="Protofilo\.git\objects\10\d066f35a22aa8094b8d517242f3434a174f868" />
    <None Include="Protofilo\.git\objects\24\c24ed96d6152ac4c7de08cb3d2aed46417fd26" />
    <None Include="Protofilo\.git\objects\26\4f459bf8765c2eeb6a818ad09ad37a9cb4ff60" />
    <None Include="Protofilo\.git\objects\47\f2db8bbe61cff38ec18c11f0a6026220437c4c" />
    <None Include="Protofilo\.git\objects\56\59fc8ed480a6f3633c37f460941ecda5489d7d" />
    <None Include="Protofilo\.git\objects\57\614f9c967596fad0a3989bec2b1deff33034f6" />
    <None Include="Protofilo\.git\objects\5d\f75f9c838ea50f80ee4d5703b68dd8ac7243d4" />
    <None Include="Protofilo\.git\objects\6b\36213cb01cb81b151856b38e5946370e3fe76e" />
    <None Include="Protofilo\.git\objects\76\1785c0049ac00f45cdd1661a3d2e71be713010" />
    <None Include="Protofilo\.git\objects\77\b374577de83b86d846eadda2dd17532d7dabaa" />
    <None Include="Protofilo\.git\objects\7d\f399c5fb765b3e8cf70d1b37c47e4ffe8565d2" />
    <None Include="Protofilo\.git\objects\7e\071e41206db17992a1552fe718e46b0434260d" />
    <None Include="Protofilo\.git\objects\90\d4ee0072ce3fc41812f8af910219f9eea3c3de" />
    <None Include="Protofilo\.git\objects\92\5af837050a4abe679c5fea0df7e41faf6fc011" />
    <None Include="Protofilo\.git\objects\a2\98b5bd8796ac377fe9ed64caa249e24c7ec3b6" />
    <None Include="Protofilo\.git\objects\b3\f1ecf44a54372bf90afbb60491417242b8769c" />
    <None Include="Protofilo\.git\objects\cc\7b141350ffde43afce3ec16ea4d7b5007cde2b" />
    <None Include="Protofilo\.git\objects\d3\9e8546bc531095fcece0e7b4056ae0ba126e45" />
    <None Include="Protofilo\.git\objects\d9\53f4c41b314eaf5b02cf0a9eff4d84598aa734" />
    <None Include="Protofilo\.git\objects\dc\39edb5f23a35f788cba146dd7337127ba6c5ab" />
    <None Include="Protofilo\.git\objects\e4\955f26b14bfa5dc1570562cbc590a7e9cb076c" />
    <None Include="Protofilo\.git\objects\e6\9de29bb2d1d6434b8b29ae775ad8c2e48c5391" />
    <None Include="Protofilo\.git\objects\e7\1dfc0743306fc2755bdfb89276b4532dc74e70" />
    <None Include="Protofilo\.git\objects\f1\66060da1cbc9f216e9f5e99a1ef6074ce2a8f8" />
    <None Include="Protofilo\.git\objects\f7\a80e25a57c33b84c0c4d053b242405090d11b9" />
    <None Include="Protofilo\.git\objects\fb\d6b7bacd0e092a57e38c68f6509ad2efffdc14" />
    <None Include="Protofilo\.git\opencode" />
    <None Include="Protofilo\.git\refs\heads\master" />
    <None Include="Protofilo\node_modules\%40babel\core\node_modules\.bin\semver" />
    <None Include="Protofilo\node_modules\%40babel\core\node_modules\.bin\semver.cmd" />
    <None Include="Protofilo\node_modules\%40babel\core\node_modules\.bin\semver.ps1" />
    <None Include="Protofilo\node_modules\%40babel\helper-compilation-targets\node_modules\.bin\semver" />
    <None Include="Protofilo\node_modules\%40babel\helper-compilation-targets\node_modules\.bin\semver.cmd" />
    <None Include="Protofilo\node_modules\%40babel\helper-compilation-targets\node_modules\.bin\semver.ps1" />
    <None Include="Protofilo\node_modules\%40npmcli\git\node_modules\.bin\node-which" />
    <None Include="Protofilo\node_modules\%40npmcli\git\node_modules\.bin\node-which.cmd" />
    <None Include="Protofilo\node_modules\%40npmcli\git\node_modules\.bin\node-which.ps1" />
    <None Include="Protofilo\node_modules\%40npmcli\promise-spawn\node_modules\.bin\node-which" />
    <None Include="Protofilo\node_modules\%40npmcli\promise-spawn\node_modules\.bin\node-which.cmd" />
    <None Include="Protofilo\node_modules\%40npmcli\promise-spawn\node_modules\.bin\node-which.ps1" />
    <None Include="Protofilo\node_modules\.bin\baseline-browser-mapping" />
    <None Include="Protofilo\node_modules\.bin\baseline-browser-mapping.cmd" />
    <None Include="Protofilo\node_modules\.bin\baseline-browser-mapping.ps1" />
    <None Include="Protofilo\node_modules\.bin\browserslist" />
    <None Include="Protofilo\node_modules\.bin\browserslist.cmd" />
    <None Include="Protofilo\node_modules\.bin\browserslist.ps1" />
    <None Include="Protofilo\node_modules\.bin\download-lmdb-prebuilds" />
    <None Include="Protofilo\node_modules\.bin\download-lmdb-prebuilds.cmd" />
    <None Include="Protofilo\node_modules\.bin\download-lmdb-prebuilds.ps1" />
    <None Include="Protofilo\node_modules\.bin\download-msgpackr-prebuilds" />
    <None Include="Protofilo\node_modules\.bin\download-msgpackr-prebuilds.cmd" />
    <None Include="Protofilo\node_modules\.bin\download-msgpackr-prebuilds.ps1" />
    <None Include="Protofilo\node_modules\.bin\esbuild" />
    <None Include="Protofilo\node_modules\.bin\esbuild.cmd" />
    <None Include="Protofilo\node_modules\.bin\esbuild.ps1" />
    <None Include="Protofilo\node_modules\.bin\installed-package-contents" />
    <None Include="Protofilo\node_modules\.bin\installed-package-contents.cmd" />
    <None Include="Protofilo\node_modules\.bin\installed-package-contents.ps1" />
    <None Include="Protofilo\node_modules\.bin\jsesc" />
    <None Include="Protofilo\node_modules\.bin\jsesc.cmd" />
    <None Include="Protofilo\node_modules\.bin\jsesc.ps1" />
    <None Include="Protofilo\node_modules\.bin\json5" />
    <None Include="Protofilo\node_modules\.bin\json5.cmd" />
    <None Include="Protofilo\node_modules\.bin\json5.ps1" />
    <None Include="Protofilo\node_modules\.bin\karma" />
    <None Include="Protofilo\node_modules\.bin\karma.cmd" />
    <None Include="Protofilo\node_modules\.bin\karma.ps1" />
    <None Include="Protofilo\node_modules\.bin\mime" />
    <None Include="Protofilo\node_modules\.bin\mime.cmd" />
    <None Include="Protofilo\node_modules\.bin\mime.ps1" />
    <None Include="Protofilo\node_modules\.bin\mkdirp" />
    <None Include="Protofilo\node_modules\.bin\mkdirp.cmd" />
    <None Include="Protofilo\node_modules\.bin\mkdirp.ps1" />
    <None Include="Protofilo\node_modules\.bin\nanoid" />
    <None Include="Protofilo\node_modules\.bin\nanoid.cmd" />
    <None Include="Protofilo\node_modules\.bin\nanoid.ps1" />
    <None Include="Protofilo\node_modules\.bin\ng" />
    <None Include="Protofilo\node_modules\.bin\ng-xi18n" />
    <None Include="Protofilo\node_modules\.bin\ng-xi18n.cmd" />
    <None Include="Protofilo\node_modules\.bin\ng-xi18n.ps1" />
    <None Include="Protofilo\node_modules\.bin\ng.cmd" />
    <None Include="Protofilo\node_modules\.bin\ng.ps1" />
    <None Include="Protofilo\node_modules\.bin\ngc" />
    <None Include="Protofilo\node_modules\.bin\ngc.cmd" />
    <None Include="Protofilo\node_modules\.bin\ngc.ps1" />
    <None Include="Protofilo\node_modules\.bin\node-gyp" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-optional" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-optional.cmd" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-optional.ps1" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-test" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-test.cmd" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages-test.ps1" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages.cmd" />
    <None Include="Protofilo\node_modules\.bin\node-gyp-build-optional-packages.ps1" />
    <None Include="Protofilo\node_modules\.bin\node-gyp.cmd" />
    <None Include="Protofilo\node_modules\.bin\node-gyp.ps1" />
    <None Include="Protofilo\node_modules\.bin\node-which" />
    <None Include="Protofilo\node_modules\.bin\node-which.cmd" />
    <None Include="Protofilo\node_modules\.bin\node-which.ps1" />
    <None Include="Protofilo\node_modules\.bin\nopt" />
    <None Include="Protofilo\node_modules\.bin\nopt.cmd" />
    <None Include="Protofilo\node_modules\.bin\nopt.ps1" />
    <None Include="Protofilo\node_modules\.bin\pacote" />
    <None Include="Protofilo\node_modules\.bin\pacote.cmd" />
    <None Include="Protofilo\node_modules\.bin\pacote.ps1" />
    <None Include="Protofilo\node_modules\.bin\parser" />
    <None Include="Protofilo\node_modules\.bin\parser.cmd" />
    <None Include="Protofilo\node_modules\.bin\parser.ps1" />
    <None Include="Protofilo\node_modules\.bin\resolve" />
    <None Include="Protofilo\node_modules\.bin\resolve.cmd" />
    <None Include="Protofilo\node_modules\.bin\resolve.ps1" />
    <None Include="Protofilo\node_modules\.bin\rimraf" />
    <None Include="Protofilo\node_modules\.bin\rimraf.cmd" />
    <None Include="Protofilo\node_modules\.bin\rimraf.ps1" />
    <None Include="Protofilo\node_modules\.bin\rollup" />
    <None Include="Protofilo\node_modules\.bin\rollup.cmd" />
    <None Include="Protofilo\node_modules\.bin\rollup.ps1" />
    <None Include="Protofilo\node_modules\.bin\sass" />
    <None Include="Protofilo\node_modules\.bin\sass.cmd" />
    <None Include="Protofilo\node_modules\.bin\sass.ps1" />
    <None Include="Protofilo\node_modules\.bin\semver" />
    <None Include="Protofilo\node_modules\.bin\semver.cmd" />
    <None Include="Protofilo\node_modules\.bin\semver.ps1" />
    <None Include="Protofilo\node_modules\.bin\tsc" />
    <None Include="Protofilo\node_modules\.bin\tsc.cmd" />
    <None Include="Protofilo\node_modules\.bin\tsc.ps1" />
    <None Include="Protofilo\node_modules\.bin\tsserver" />
    <None Include="Protofilo\node_modules\.bin\tsserver.cmd" />
    <None Include="Protofilo\node_modules\.bin\tsserver.ps1" />
    <None Include="Protofilo\node_modules\.bin\ua-parser-js" />
    <None Include="Protofilo\node_modules\.bin\ua-parser-js.cmd" />
    <None Include="Protofilo\node_modules\.bin\ua-parser-js.ps1" />
    <None Include="Protofilo\node_modules\.bin\update-browserslist-db" />
    <None Include="Protofilo\node_modules\.bin\update-browserslist-db.cmd" />
    <None Include="Protofilo\node_modules\.bin\update-browserslist-db.ps1" />
    <None Include="Protofilo\node_modules\.bin\vite" />
    <None Include="Protofilo\node_modules\.bin\vite.cmd" />
    <None Include="Protofilo\node_modules\.bin\vite.ps1" />
    <None Include="Protofilo\node_modules\balanced-match\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\call-bind-apply-helpers\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\call-bound\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\dunder-proto\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\ent\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\es-define-property\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\es-errors\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\es-object-atoms\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\fast-uri\.github\dependabot.yml" />
    <None Include="Protofilo\node_modules\fast-uri\.github\workflows\ci.yml" />
    <None Include="Protofilo\node_modules\fast-uri\.github\workflows\lock-threads.yml" />
    <None Include="Protofilo\node_modules\fast-uri\.github\workflows\package-manager-ci.yml" />
    <None Include="Protofilo\node_modules\function-bind\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\function-bind\.github\SECURITY.md" />
    <None Include="Protofilo\node_modules\get-intrinsic\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\get-proto\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\gopd\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\has-symbols\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\has-tostringtag\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\hasown\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\json-schema-traverse\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\json-schema-traverse\.github\workflows\build.yml" />
    <None Include="Protofilo\node_modules\json-schema-traverse\.github\workflows\publish.yml" />
    <None Include="Protofilo\node_modules\karma-chrome-launcher\node_modules\.bin\which" />
    <None Include="Protofilo\node_modules\karma-chrome-launcher\node_modules\.bin\which.cmd" />
    <None Include="Protofilo\node_modules\karma-chrome-launcher\node_modules\.bin\which.ps1" />
    <None Include="Protofilo\node_modules\karma-coverage\node_modules\.bin\semver" />
    <None Include="Protofilo\node_modules\karma-coverage\node_modules\.bin\semver.cmd" />
    <None Include="Protofilo\node_modules\karma-coverage\node_modules\.bin\semver.ps1" />
    <None Include="Protofilo\node_modules\karma\node_modules\qs\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\karma\node_modules\qs\.github\SECURITY.md" />
    <None Include="Protofilo\node_modules\karma\node_modules\qs\.github\THREAT_MODEL.md" />
    <None Include="Protofilo\node_modules\lmdb\dependencies\lz4\lib\dll\example\fullbench-dll.sln" />
    <None Include="Protofilo\node_modules\lmdb\dependencies\lz4\lib\dll\example\fullbench-dll.vcxproj" />
    <None Include="Protofilo\node_modules\math-intrinsics\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\minimist\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\node-gyp\node_modules\.bin\node-which" />
    <None Include="Protofilo\node_modules\node-gyp\node_modules\.bin\node-which.cmd" />
    <None Include="Protofilo\node_modules\node-gyp\node_modules\.bin\node-which.ps1" />
    <None Include="Protofilo\node_modules\object-inspect\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\ordered-binary\.idea\ordered-binary.iml" />
    <None Include="Protofilo\node_modules\qs\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\qs\.github\SECURITY.md" />
    <None Include="Protofilo\node_modules\qs\.github\THREAT_MODEL.md" />
    <None Include="Protofilo\node_modules\resolve\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\rfdc\.github\workflows\ci.yml" />
    <None Include="Protofilo\node_modules\safe-regex-test\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\side-channel-list\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\side-channel-map\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\side-channel-weakmap\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\side-channel\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\supports-preserve-symlinks-flag\.github\FUNDING.yml" />
    <None Include="Protofilo\node_modules\zod-to-json-schema\.github\FUNDING.yml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Protofilo\.git\objects\info\" />
    <Folder Include="Protofilo\.git\objects\pack\" />
    <Folder Include="Protofilo\.git\refs\tags\" />
  </ItemGroup>

</Project>
